### ISSUE TITLE
Generate feed by language and currency

### ISSUE THREAD

**Issue by flebap** [shoppingflux/shoppingfluxexport#35]
## Expected behaviour

Allow to generate a feed by language and/or currency + Store

feed_en.xml
feed_en_gbp.xml
feed_en_gbp_idstore.xml
## Actual behaviour

The feed contains the default language and currency

**Comment by clement-hollander** [comment]
@Vincent-Coll this is not working as expected : http://ps-dev.shopping-feed.com/modules/shoppingfluxexport/flux.php?token=df74510996704c2a0c855c5e69500357&lang=es&currency=2

we need to use the id of the currency, but we can't know each it changes between each Prestashop client. We should be able to use currency iso code : http://ps-dev.shopping-feed.com/modules/shoppingfluxexport/flux.php?token=df74510996704c2a0c855c5e69500357&lang=es&currency=MXN

Otherwise the cron feature works well

**Comment by Vincent-Profileo** [comment]
@clement-hollander 
Hello,
We modified it and commited.
Please confirm

**Comment by clement-hollander** [comment]
@Vincent-Coll thanks this is now good
