### ISSUE TITLE
stock set to 0

### ISSUE THREAD

**Issue by Alexandre17220** [shoppingflux/shoppingfluxexport#382]
Hi All,
My customer have installed this module to his prestashop 1.7.3.3.
After configuration (set by my customer) much products (95%) have stock set to 0 in prestashop...
I don't understand why this module update stock and how is problem came?
I am developper. I make some module for prestashop and other solution.

Thanks,

**Comment by MathieuSF** [comment]
Hello Alexandre, 

Our module does not change stock data.
The only change can be made on quantities are related to order importation from marketplace through Shopping Feed.

The best way to manage this issue is to create a ticket to our support team (support@shopping-flux.com), and they will help you (or your customer) to analyse and solve this problem.

Thanks,
Mathieu.
